chore: update Android Zendesk module to allow sending of tags
endpointclosing/react-native-zendesk-chat pull request #2
Opened 2020-09-30 20:03 UTC by zoofan

2020-10-01 21:48 UTC, paustria requested changes

2020-10-01 21:48 UTC, paustria commented on android/src/main/java/com/taskrabbit/zendesk/RNZendeskChatModule.java
> +            builder.name("name");
Why do you update this?

2020-10-01 21:48 UTC, paustria commented on android/src/main/java/com/taskrabbit/zendesk/RNZendeskChatModule.java
> +        PreChatForm preChatForm = new PreChatForm.Builder()
I don't think we need prechat form.

2020-10-05 17:21 UTC, zoofan commented on android/src/main/java/com/taskrabbit/zendesk/RNZendeskChatModule.java
> +            builder.name("name");
Fixed.

2020-10-05 17:21 UTC, zoofan commented on android/src/main/java/com/taskrabbit/zendesk/RNZendeskChatModule.java
> +        PreChatForm preChatForm = new PreChatForm.Builder()
You're right. Removed.

2020-10-05 17:29 UTC, paustria commented
@zoofan Could you please resolve conflict?

2020-10-07 22:48 UTC, binhxn approved these changes

2020-10-07 23:08 UTC, paustria approved these changes

2020-10-08 00:43 UTC, merged